---
# Copyright (c) 2020, 2021 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name: 인스턴스를 생성하고 SSH를 사용하여 연결한다.
  hosts: localhost
  collections:
    - oracle.oci

  vars:
    ansible_python_interpreter: /usr/bin/python3
    # common networking definitions
    quad_zero_route: "0.0.0.0/0"
    TCP_protocol: "6"
    SSH_port: "22"

    vcn_name: "vnc02"
    vcn_cidr_block: "192.168.0.0/16"
    vcn_dns_label: "vcn02"

    ig_name: "igw"

    route_table_name: "igw route table"
    # route all internet access to our Internet Gateway
    route_table_rules:
        - cidr_block: "{{ quad_zero_route }}"
          network_entity_id: "{{ ig_id }}"


    subnet_cidr: "192.168.1.0/24"
    subnet_name: "public subnet"
    subnet_dns_label: "publicsubnet"

    securitylist_name: "mysecuritylist"

    instance_shape: "{{ lookup('env', 'SAMPLE_INSTANCE_SHAPE') | default('VM.Standard.E2.1', true) }}"
    instance_hostname: "mytestinstance"

    #########################################
    # 가용성 도메인, 구획, 이미지ID를 변수로 지정한다.
    #########################################
    instance_ad: "instance_ad"
    instance_compartment: "instance_compartment"
    instance_image: "instance_image"

  tasks:
    - block:
      - import_tasks: setup.yaml
      - set_fact:
          SSH_AUTHORIZED_KEYS: "{{ lookup('env', 'SAMPLE_PUBLIC_SSH_KEY') if 'SAMPLE_PUBLIC_SSH_KEY' in ansible_env else lookup('file',  my_test_public_key ) }}"

      - name: 인스턴스 생성
        oci_compute_instance:
          availability_domain: "{{ instance_ad }}"
          compartment_id: "{{ instance_compartment }}"
          name: "my_test_instance"
          image_id: "{{ instance_image }}"
          shape: "{{ instance_shape }}"
          create_vnic_details:
              assign_public_ip: True
              hostname_label: "{{ instance_hostname }}"
              subnet_id: "{{ instance_subnet_id }}"
          metadata:
              ssh_authorized_keys: "{{ SSH_AUTHORIZED_KEYS }}"
        register: result

      - name: 인스턴스 상세 정보 출력
        debug:
          msg: "Launched a new instance {{ result }}"
      - set_fact:
          instance_id: "{{ result.instance.id }}"

      - name: 인스턴스의 VNIC 세부 정보 가져오기
        oci_compute_vnic_attachment_facts:
          compartment_id: "{{ instance_compartment }}"
          instance_id: "{{ instance_id }}"
        register: result

      - name: 인스턴스 세부 정보 표시
        oci_network_vnic_facts:
          id: "{{ result.vnic_attachments[0].vnic_id }}"
        register: result
      - set_fact:
          instance_public_ip: "{{result.vnic.public_ip}}"

      - name: 인스턴스의 공인 IP 가져오기
        debug:
          msg: "Public IP of launched instance {{ instance_public_ip }}"

      - name: 포트 22번이 열릴 때까지 대기(10초)
        wait_for:
          port: 22
          host: '{{ instance_public_ip }}'
          state: started
          delay: 10
          timeout: 600
        vars:
          ansible_connection: local

      - set_fact:
          # opc 사용자 사용
          # Disable SSH's strict host key checking just for this one command invocation
          ssh_command_with_generated_key: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -i {{ temp_certificates_path }}/private_key.pem opc@{{ instance_public_ip }} uname -a
        when: "'SAMPLE_PUBLIC_SSH_KEY' not in ansible_env"
      
      - set_fact:
          # opc 사용자 사용
          # Disable SSH's strict host key checking just for this one command invocation
          ssh_command_with_custom_key: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" opc@{{ instance_public_ip }} uname -a
        when: "'SAMPLE_PUBLIC_SSH_KEY' in ansible_env"

      - name: SSH 연결 시도
        command: "{{ ssh_command_with_custom_key if 'SAMPLE_PUBLIC_SSH_KEY' in ansible_env else ssh_command_with_generated_key }}"
        retries: 3
        delay: 5
        register: result
        until: result.rc == 0

      - name: SSH 응답을 출력
        debug:
          msg: "SSH response from instance -> {{ result.stdout_lines }}"

      - import_tasks: teardown.yaml

      rescue:

        - import_tasks: teardown.yaml